class BistIndexMembership {
  BistIndexMembership._();

  static const Set<String> bist30 = {
    'AEFES',
    'AKBNK',
    'ASELS',
    'ASTOR',
    'BIMAS',
    'DSTKF',
    'EKGYO',
    'ENKAI',
    'EREGL',
    'FROTO',
    'GARAN',
    'GUBRF',
    'ISCTR',
    'KCHOL',
    'KRDMD',
    'MGROS',
    'PETKM',
    'PGSUS',
    'SAHOL',
    'SASA',
    'SISE',
    'TAVHL',
    'TCELL',
    'THYAO',
    'TOASO',
    'TRALT',
    'TTKOM',
    'TUPRS',
    'VAKBN',
    'YKBNK',
  };

  static const Set<String> bist50 = {
    'AEFES',
    'AKBNK',
    'AKSEN',
    'ALARK',
    'ASELS',
    'ASTOR',
    'BIMAS',
    'BRSAN',
    'BTCIM',
    'CCOLA',
    'CIMSA',
    'DOHOL',
    'DSTKF',
    'ECILC',
    'EFOR',
    'EKGYO',
    'ENKAI',
    'EREGL',
    'FROTO',
    'GARAN',
    'GLRMK',
    'GUBRF',
    'HALKB',
    'HEKTS',
    'ISCTR',
    'KCHOL',
    'KRDMD',
    'KTLEV',
    'KUYAS',
    'MGROS',
    'MIATK',
    'OYAKC',
    'PASEU',
    'PETKM',
    'PGSUS',
    'SAHOL',
    'SASA',
    'SISE',
    'SOKM',
    'TAVHL',
    'TCELL',
    'THYAO',
    'TOASO',
    'TRALT',
    'TRMET',
    'TTKOM',
    'TUPRS',
    'ULKER',
    'VAKBN',
    'YKBNK',
  };
  static const Set<String> bist100 = {
    'AEFES',
    'AKBNK',
    'AKSA',
    'AKSEN',
    'ALARK',
    'ALTNY',
    'ANSGR',
    'ARCLK',
    'ASELS',
    'ASTOR',
    'BALSU',
    'BERA',
    'BIMAS',
    'BRSAN',
    'BRYAT',
    'BSOKE',
    'BTCIM',
    'CANTE',
    'CCOLA',
    'CIMSA',
    'CVKMD',
    'CWENE',
    'DAPGM',
    'DOAS',
    'DOHOL',
    'DSTKF',
    'ECILC',
    'EFOR',
    'EKGYO',
    'ENERY',
    'ENJSA',
    'ENKAI',
    'EREGL',
    'ESEN',
    'EUPWR',
    'EUREN',
    'FENER',
    'FROTO',
    'GARAN',
    'GENIL',
    'GESAN',
    'GLRMK',
    'GRSEL',
    'GRTHO',
    'GSRAY',
    'GUBRF',
    'HALKB',
    'HEKTS',
    'IEYHO',
    'ISCTR',
    'ISMEN',
    'IZENR',
    'KCHOL',
    'KLRHO',
    'KRDMD',
    'KTLEV',
    'KUYAS',
    'MAGEN',
    'MAVI',
    'MGROS',
    'MIATK',
    'MPARK',
    'OBAMS',
    'ODAS',
    'ODINE',
    'OTKAR',
    'OYAKC',
    'PAHOL',
    'PASEU',
    'PATEK',
    'PETKM',
    'PGSUS',
    'PSGYO',
    'QUAGR',
    'RALYH',
    'REEDR',
    'SAHOL',
    'SARKY',
    'SASA',
    'SISE',
    'SKBNK',
    'SOKM',
    'TAVHL',
    'TCELL',
    'THYAO',
    'TKFEN',
    'TOASO',
    'TRALT',
    'TRENJ',
    'TRMET',
    'TSKB',
    'TTKOM',
    'TUKAS',
    'TUPRS',
    'TURSG',
    'ULKER',
    'VAKBN',
    'VESTL',
    'YKBNK',
    'ZOREN',
  };

  static bool isBist30(String symbol) => bist30.contains(symbol.toUpperCase());

  static bool isBist50(String symbol) => bist50.contains(symbol.toUpperCase());

  static bool isBist100(String symbol) =>
      bist100.contains(symbol.toUpperCase());

  static String label(String symbol) {
    final code = symbol.toUpperCase();

    if (bist30.contains(code)) return 'B30';
    if (bist50.contains(code)) return 'B50';
    if (bist100.contains(code)) return 'B100';
    return 'BIST';
  }
}
